# https://github.com/robvanderleek/create-issue-branch
on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]
  # The issue_comment event below is only needed for the ChatOps mode,
  # you can remove it otherwise
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
mode: chatops
defaultBranch: main
branchName: '${issue.number}-${issue.title}'
silent: false
autoCloseIssue: true
gitSafeReplacementChar: '-'
commentMessage: >
  "Branch ${branchName} created! Clone with:\n
  `git fetch && git checkout --track origin/${branchName}`\n
  Rebase `develop` branch changes with:\n
  `git checkout ${branchName} && git rebase develop`"
