# https://github.com/robvanderleek/create-issue-branch
mode: chatops
defaultBranch: main
branchName: '${issue.number}-${issue.title}'
silent: false
autoCloseIssue: true
gitSafeReplacementChar: '-'

branches:
  - label: enhancement
    name: dev
    prefix: feature/

  - label: bug
    name: staging
    prefix: bugfix/${issue.assignee.login}/

  - label: '*'
    skip: true

commentMessage: "Branch ${branchName} created! Clone with:\n`git fetch && git checkout --track origin/${branchName}`\n\nRebase `develop` branch changes with:`git checkout ${branchName} && git rebase develop`"
