# https://github.com/robvanderleek/create-issue-branch
#mode: chatops
#branchName: '${issue.number}-${issue.title}'
branchName: short
silent: false
autoCloseIssue: true
gitSafeReplacementChar: '-'

branches:
  - label: hotfix
    name: stable
    prefix: hotfix/
    
  - label: enhancement
    name: main
    prefix: feature/

  - label: scope
    name: main
    prefix: feature/    

  - label: bug
    name: main
    prefix: bugfix/

  - label: '*'
    skip: true

commentMessage: "Branch `${branchName}` created! \n\nClone with:\n> `git fetch && git checkout --track origin/${branchName}`\n\nNeed to [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)?\n\n**For features, bugfixes:** Rebase `main` branch changes with:\n> `git checkout ${branchName} && git rebase main`\n\n**For hotfixes:** Rebase `stable` branch changes with:\n> `git checkout ${branchName} && git rebase stable`\n\nLearn more about [git branching](https://github.com/bytelaunch/project-development-process/wiki/git-branching)..."
