name: Issue Title Checker
on:
  issues:
    types: [ opened ]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Issue title checker
        uses: IndyV/IssueChecker@v1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: |
            The issue title must confirm to the conventional commit standard. For example:
            
            \<type\>[optional scope]: \<description\>
            
            Available types:
                - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
                - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
                - docs: Documentation only changes
                - feat: A new feature
                - fix: A bug fix
                - perf: A code change that improves performance
                - refactor: A code change that neither fixes a bug nor adds a feature
                - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
                - test: Adding missing tests or correcting existing tests
            
            For more information, see https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines
          issue-pattern: "^((?!((build|chore|ci|docs|feat|fix|perf|refactor|revert|style)(\\([a-z\\-]+\\))?\\!?:)+)).*$"
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          include-title: 1
          include-body: 0
          not-before: 2020-01-15T02:54:32Z
          enable-versioned-regex: 0
