- name: Issue title checker
  # You may pin to the exact commit or the version.
  # uses: IndyV/IssueChecker@462e596bd238c175e3790b0bce0ee8b03817ff32
  uses: IndyV/IssueChecker@v1.0
  with:
    # Message content to comment on the issue before closing
    issue-close-message: |
        The issue title must confirm to the conventional commit standard. For example:
        
        <type>[optional scope]: <description>
        
        Available types:
            - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
            - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
            - docs: Documentation only changes
            - feat: A new feature
            - fix: A bug fix
            - perf: A code change that improves performance
            - refactor: A code change that neither fixes a bug nor adds a feature
            - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
            - test: Adding missing tests or correcting existing tests
            
        For more information, see 
    # Regular expression pattern, if the issue title matches the regex it will be closed
    issue-pattern: ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)
    # GitHub token
    repo-token: ${{ secrets.GITHUB_TOKEN }}
